tests/encode: Move pedantic and conversion test
The float tests in test3 need newlib to compile (to avoid
"undefined reference to `__aeabi_f2uiz'"). But newlib doesn't compile
with pedantic because it uses #include_next

Signed-off-by: Øyvind Rønningstad <oyvind.ronningstad@nordicsemi.no>